import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "디어드림",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <main>
      
      {/* {children={loggedIn}} */}
      {children}
    </main>
  );
}
